# Generated by Django 4.0.5 on 2022-06-05 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hittegods',
            fields=[
                ('lopenummer', models.AutoField(primary_key=True, serialize=False)),
                ('tilleggsinfo', models.TextField()),
                ('naarMistet', models.DateTimeField()),
                ('hvorMistet', models.CharField(max_length=255)),
                ('naarFunnet', models.DateTimeField()),
                ('hvorFunnet', models.CharField(max_length=255)),
                ('registreringsTidspunkt', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobilnummer', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NO')),
                ('navn', models.CharField(max_length=255)),
                ('gruppe', models.CharField(blank=True, max_length=255)),
                ('plassering', models.CharField(blank=True, max_length=255, null=True)),
                ('utlevertTil', models.CharField(blank=True, max_length=255)),
                ('utlevertAv', models.CharField(blank=True, max_length=255)),
                ('utlevertNaar', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_navn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utfodring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('navn', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Oppdatering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registreringsTidspunkt', models.DateTimeField(default=django.utils.timezone.now)),
                ('beskrivelse', models.TextField()),
                ('hittegods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hittegods.hittegods')),
            ],
        ),
        migrations.AddField(
            model_name='hittegods',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hittegods.kategori'),
        ),
        migrations.AddField(
            model_name='hittegods',
            name='utfodring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hittegods.utfodring'),
        ),
    ]
