# Generated by Django 4.0.5 on 2022-06-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hittegods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hittegods',
            old_name='hvorFunnet',
            new_name='funnet_sted',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='naarFunnet',
            new_name='funnet_tidspunkt',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='hvorMistet',
            new_name='mistet_sted',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='naarMistet',
            new_name='mistet_tidspunkt',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='registreringsTidspunkt',
            new_name='registreringstidspunkt',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='utlevertAv',
            new_name='utlevert_av',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='utlevertNaar',
            new_name='utlevert_tidspunkt',
        ),
        migrations.RenameField(
            model_name='hittegods',
            old_name='utlevertTil',
            new_name='utlevert_til',
        ),
    ]
