# Generated by Django 4.0.5 on 2022-06-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hittegods', '0003_alter_hittegods_oppdatert_tidspunkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittegods',
            name='oppdatert_tidspunkt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hittegods',
            name='registreringstidspunkt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
