# Generated by Django 4.0.5 on 2022-06-28 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hittegods', '0004_alter_hittegods_oppdatert_tidspunkt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittegods',
            name='registreringstidspunkt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
