# Generated by Django 4.0.5 on 2022-06-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hittegods', '0005_alter_hittegods_registreringstidspunkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NyligOppdatert',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Hittegods - Nylig oppdatert',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hittegods.hittegods',),
        ),
    ]
